spring:
  profiles: peer2
server:
  port: 8890
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer2:8889/eureka/      

management:
  port: 9002
  security: 
    enabled: false        