eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8889/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-hi
  redis:
    host: 118.25.5.22
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 500  
server:
  port: 8763
  
  
  
  